/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_OrganoidBrain
#define _Included_OrganoidBrain
#ifdef __cplusplus
extern "C" {
#endif

// Метод для кормления
JNIEXPORT void JNICALL Java_OrganoidBrain_feedVasya(JNIEnv *, jobject, jstring);

// Метод для общения (RU/AR)
JNIEXPORT jstring JNICALL Java_OrganoidBrain_askQuestion(JNIEnv *, jobject, jstring);

// Метод для написания кода
JNIEXPORT jstring JNICALL Java_OrganoidBrain_writeCode(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif /* _Included_OrganoidBrain */